FROM maven:3.9.12-eclipse-temurin-25 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn -q -DskipTests package

FROM eclipse-temurin:25-jre
WORKDIR /app

COPY --from=build /app/target/*.jar /app/app.jar

RUN mkdir -p /app/uploads/plants

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
